#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_HOME="$(cd "${0%/*}" && pwd -P)"
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
darwin=false
msys=false
case "$(uname)" in
    CYGWIN* )
        cygwin=true
        ;;
    Darwin* )
        darwin=true
        ;;
    MINGW* )
        msys=true
        ;;
esac

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
if [ -h "$0" ] ; then
    ls=$(ls -ld "$0")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        APP_HOME=$link
    else
        APP_HOME=$(dirname "$0")/$link
    fi
fi

# If JAVA_HOME is not set, try to detect it
if [ -z "$JAVA_HOME" ]; then
    if $darwin; then
        if [ -x "/usr/libexec/java_home" ]; then
            JAVA_HOME=$(/usr/libexec/java_home)
        fi
    fi
fi

if [ -z "$JAVA_HOME" ]; then
    javaExecutable=$(command -v java)
    if [ -x "$javaExecutable" ]; then
        JAVA_HOME=$(dirname "$javaExecutable")/..
    else
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    fi
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

if [ -n "$JAVA_HOME" ]; then
    JAVA_HOME=$(cd "$JAVA_HOME" && pwd -P)
fi

if [ "$cygwin" = "true" ] || [ "$msys" = "true" ]; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")
fi

# Increase the maximum file descriptors if possible.
if [ "$cygwin" = "false" ] && [ "$darwin" = "false" ]; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ]; then
        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ]; then
            MAX_FD=$MAX_FD_LIMIT
        fi
        ulimit -n $MAX_FD
    fi
fi

# Set ANDROID_HOME if not already set (for React Native builds from source)
if [ -z "$ANDROID_HOME" ] && [ -z "$ANDROID_SDK_ROOT" ]; then
    if [ -d "$HOME/Library/Android/sdk" ]; then
        export ANDROID_HOME="$HOME/Library/Android/sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
    elif [ -d "$HOME/Android/Sdk" ]; then
        export ANDROID_HOME="$HOME/Android/Sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
    fi
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

